const initialData = {
  letters: {
    'letter1': { id: 'letter1', content: `B`},
    'letter2': { id: 'letter2', content: 'F'},
    'letter3': { id: 'letter3', content: 'K'},
    'letter4': { id: 'letter4', content: 'J'},
    'letter5': { id: 'letter5', content: 'Q'},
    'letter6': { id: 'letter6', content: 'S'},
    'letter7': { id: 'letter7', content: 'A'},
    'letter8': { id: 'letter8', content: 'E'},
    'letter9': { id: 'letter9', content: 'T'},
    'letter10': { id: 'letter10', content: 'G'},
    'letter11': { id: 'letter11', content: 'O'},
    'letter12': { id: 'letter12', content: 'I'},
    'letter13': { id: 'letter13', content: 'C'},
    'letter14': { id: 'letter14', content: 'H'},
    'letter15': { id: 'letter15', content: 'O'},
    'letter16': { id: 'letter16', content: 'E'},
    'letter17': { id: 'letter17', content: 'P'},
    'letter18': { id: 'letter18', content: 'R'},
    'letter19': { id: 'letter19', content: 'N'},
    'letter20': { id: 'letter20', content: 'D'},
    'letter21': { id: 'letter21', content: 'C'},
    'letter22': { id: 'letter22', content: 'Y'},
    'letter23': { id: 'letter23', content: 'L'},
    'letter24': { id: 'letter24', content: 'H'},
    'letter25': { id: 'letter25', content: 'A'},
    'letter26': { id: 'letter26', content: 'U'},
  },
  columns: {
    'column1': {
      id: 'column1',
      title: 'Set of letters',
      letterIds: [
        'letter1',
        'letter2',
        'letter3',
        'letter4',
        'letter5',
        'letter6',
        'letter7',
        'letter8',
        'letter9',
        'letter10',
        'letter11',
        'letter12',
        'letter13',
        'letter14',
        'letter15',
        'letter16',
        'letter17',
        'letter18',
        'letter19',
        'letter20',
        'letter21',
        'letter22',
        'letter23',
        'letter24',
        'letter25',
        'letter26',
      ],
    },
    'column2': {
      id: 'column2',
      title: 'Letter',
      letterIds: [],
    },
  },
  columnOrder: [ 'column1', 'column2']
};

export default initialData;
