const initialData = {
  letters: {
    'letter1': { id: 'letter1', content: 'B'},
    'letter2': { id: 'letter2', content: 'B'},
    'letter3': { id: 'letter3', content: 'E'},
    'letter4': { id: 'letter4', content: 'E'},
    'letter5': { id: 'letter5', content: 'A'},
    'letter6': { id: 'letter6', content: 'A'},
    'letter7': { id: 'letter7', content: 'R'},
    'letter8': { id: 'letter8', content: 'I'},
    'letter9': { id: 'letter9', content: 'D'},
    'letter10': { id: 'letter10', content: 'C'},
    'letter11': { id: 'letter11', content: 'C'},
    'letter12': { id: 'letter12', content: 'T'},
    'letter13': { id: 'letter13', content: 'T'},
    'letter14': { id: 'letter14', content: 'H'},
    'letter15': { id: 'letter15', content: 'H'},
    'letter16': { id: 'letter16', content: 'K'},
    'letter17': { id: 'letter17', content: 'N'},
    'letter18': { id: 'letter18', content: 'O'},
    'letter19': { id: 'letter19', content: 'G'},
    'letter20': { id: 'letter20', content: 'L'},
    'letter21': { id: 'letter21', content: 'P'},
    'letter22': { id: 'letter22', content: 'F'},
    'letter23': { id: 'letter23', content: 'F'},
    'letter24': { id: 'letter24', content: 'S'},
    'letter25': { id: 'letter25', content: 'J'},
    'letter26': { id: 'letter26', content: 'U'},
    'letter27': { id: 'letter27', content: 'Y'},
    'letter28': { id: 'letter28', content: 'X'},
    'letter29': { id: 'letter29', content: 'M'},
    'letter30': { id: 'letter30', content: 'O'},
    'letter31': { id: 'letter31', content: 'M'},
    'letter32': { id: 'letter32', content: 'R'},
    'letter33': { id: 'letter33', content: 'R'},
    'letter34': { id: 'letter34', content: 'R'},
    'letter35': { id: 'letter35', content: 'L'},
    'letter36': { id: 'letter36', content: 'W'},
  },
  columns: {
    'column1': {
      id: 'column1',
      title: 'Set of letters',
      letterIds: [
        'letter1',
        'letter2',
        'letter3',
        'letter4',
        'letter5',
        'letter6',
        'letter7',
        'letter8',
        'letter9',
        'letter10',
        'letter11',
        'letter12',
        'letter13',
        'letter14',
        'letter15',
        'letter16',
        'letter17',
        'letter18',
        'letter19',
        'letter20',
        'letter21',
        'letter22',
        'letter23',
        'letter24',
        'letter25',
        'letter26',
        'letter27',
        'letter28',
        'letter29',
        'letter30',
        'letter31',
        'letter32',
        'letter33',
        'letter34',
        'letter35',
        'letter36',
      ],
    },
    'column2': {
      id: 'column2',
      title: 'Word',
      letterIds: [],
    },
  },
  columnOrder: [ 'column1', 'column2'],
};

export default initialData;
